spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/patient_db_dev
spring.datasource.username=postgres
spring.datasource.password=1

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

app.welcome=Chao mung toi BV RikkeiEducation

spring.datasource.password={cipher}chuoi_ma_hoa_loang_ngoang_cua_ban_o_day