spring.application.name=medical-gateway
server.port=8080

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Spring Cloud Gateway Server WebFlux Routing Configuration
# 1. Route t?i Patient-Service
spring.cloud.gateway.server.webflux.routes[0].id=patient-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://patient-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/patients/**

# 2. Route t?i Doctor-Service
spring.cloud.gateway.server.webflux.routes[1].id=doctor-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://doctor-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/doctors/**

# 3. Route t?i Appointment-Service
spring.cloud.gateway.server.webflux.routes[2].id=appointment-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://appointment-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/appointments/**