spring.application.name=appointment-service

server.port=8083

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/enpointment_db
spring.datasource.username=postgres
spring.datasource.password=1

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


# 1. C?u hình Circuit Breaker cho instance tên là 'doctorServiceCB'
# T? l? th?t b?i ng??ng (%) ?? chuy?n sang tr?ng thái OPEN
resilience4j.circuitbreaker.instances.doctorServiceCB.failure-rate-threshold=50

# S? l??ng request t?i thi?u c?n thu th?p ?? b?t ??u tính t? l? l?i
resilience4j.circuitbreaker.instances.doctorServiceCB.minimum-number-of-calls=5

# Th?i gian gi? ? tr?ng thái OPEN tr??c khi chuy?n sang HALF-OPEN (10 giây)
resilience4j.circuitbreaker.instances.doctorServiceCB.wait-duration-in-open-state=10s

# S? l??ng request cho phép th? nghi?m ? tr?ng thái HALF-OPEN
resilience4j.circuitbreaker.instances.doctorServiceCB.permitted-number-of-calls-in-half-open-state=3

# 2. C?u hình Log ?? quan sát vi?c chuy?n tr?ng thái m?ch
logging.level.io.github.resilience4j=DEBUG
