spring.application.name=appointment-service

server.port=8083

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/enpointment_db
spring.datasource.username=postgres
spring.datasource.password=1

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/



# Ten instance: doctorServiceCB
resilience4j.circuitbreaker.instances.doctorServiceCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.doctorServiceCB.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.doctorServiceCB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.doctorServiceCB.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.doctorServiceCB.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.doctorServiceCB.sliding-window-size=5

# Bat Log DEBUG cho Resilience4j
logging.level.io.github.resilience4j=DEBUG
